/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"usuarios/db"
	sw "usuarios/go"
)

func main() {
	db.InitDatabase()
	defer db.DB.Close()

	usuariosAPI := &sw.UsuariosAPI{DB: db.DB}
	artistasAPI := &sw.ArtistasAPI{DB: db.DB}
	postsAPI := &sw.PostsDeComunidadAPI{DB: db.DB}
	
	routes := sw.ApiHandleFunctions{
		UsuariosAPI: *usuariosAPI,
		ArtistasAPI: *artistasAPI,
		PostsDeComunidadAPI: *postsAPI,
	}

	log.Printf("Servidor iniciado")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
