/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"usuarios/middleware"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"time"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	
	// El middleware decide si aplicar autenticación basándose en el endpoint
	router.Use(func(c *gin.Context) {
		// Rutas públicas
		rutasPublicas := map[string]bool {
			"POST /usuarios": true,
			"GET /usuarios": true,
			"GET /artistas/:idArtista": true,
			"GET /usuarios/:idUsuario": true,
		}

		// Se formatea la clave de la ruta actual
		claveRuta := c.Request.Method + " " + c.FullPath()

		// Se comprueba si la ruta está entre las públicas
		if !rutasPublicas[claveRuta] {
			authMiddleware := middleware.Auth()
			authMiddleware(c)
		}

		c.Next()
	})

	// Agregar el middleware CORS globalmente
	router.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:5173"}, // Permite solo el frontend local en el puerto 5173
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))
	// Se añaden las rutas
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the AlbumesDeseadosAPI part of the API
	AlbumesDeseadosAPI AlbumesDeseadosAPI
	// Routes for the ComprasAPI part of the API
	ComprasAPI ComprasAPI
	// Routes for the FavoritosAPI part of the API
	FavoritosAPI FavoritosAPI
	// Routes for the ListasDeReproduccionAPI part of the API
	ListasDeReproduccionAPI ListasDeReproduccionAPI
	// Routes for the PostsDeComunidadAPI part of the API
	PostsDeComunidadAPI PostsDeComunidadAPI
	// Routes for the UsuariosAPI part of the API
	UsuariosAPI UsuariosAPI
	// Routes for the ArtistasAPI part of the API
	ArtistasAPI ArtistasAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"ArtistasIdArtistaGet",
			http.MethodGet,
			"/artistas/:idArtista",
			handleFunctions.ArtistasAPI.ArtistasIdArtistaGet,
		},
		{
			"UsuariosIdUsuarioDeseosAlbumsGet",
			http.MethodGet,
			"/usuarios/:idUsuario/deseos/albums",
			handleFunctions.AlbumesDeseadosAPI.UsuariosIdUsuarioDeseosAlbumsGet,
		},
		{
			"UsuariosIdUsuarioDeseosAlbumsIdAlbumDelete",
			http.MethodDelete,
			"/usuarios/:idUsuario/deseos/albums/:idAlbum",
			handleFunctions.AlbumesDeseadosAPI.UsuariosIdUsuarioDeseosAlbumsIdAlbumDelete,
		},
		{
			"UsuariosIdUsuarioDeseosAlbumsIdAlbumPost",
			http.MethodPost,
			"/usuarios/:idUsuario/deseos/albums/:idAlbum",
			handleFunctions.AlbumesDeseadosAPI.UsuariosIdUsuarioDeseosAlbumsIdAlbumPost,
		},
		{
			"UsuariosIdUsuarioComprasGet",
			http.MethodGet,
			"/usuarios/:idUsuario/compras",
			handleFunctions.ComprasAPI.UsuariosIdUsuarioComprasGet,
		},
		{
			"UsuariosIdUsuarioComprasIdMerchPost",
			http.MethodPost,
			"/usuarios/:idUsuario/compras/:idMerch",
			handleFunctions.ComprasAPI.UsuariosIdUsuarioComprasIdMerchPost,
		},
		{
			"UsuariosIdUsuarioFavoritosAlbumsGet",
			http.MethodGet,
			"/usuarios/:idUsuario/favoritos/albums",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosAlbumsGet,
		},
		{
			"UsuariosIdUsuarioFavoritosAlbumsIdAlbumDelete",
			http.MethodDelete,
			"/usuarios/:idUsuario/favoritos/albums/:idAlbum",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosAlbumsIdAlbumDelete,
		},
		{
			"UsuariosIdUsuarioFavoritosAlbumsIdAlbumPost",
			http.MethodPost,
			"/usuarios/:idUsuario/favoritos/albums/:idAlbum",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosAlbumsIdAlbumPost,
		},
		{
			"UsuariosIdUsuarioFavoritosArtistasGet",
			http.MethodGet,
			"/usuarios/:idUsuario/favoritos/artistas",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosArtistasGet,
		},
		{
			"UsuariosIdUsuarioFavoritosArtistasIdArtistaDelete",
			http.MethodDelete,
			"/usuarios/:idUsuario/favoritos/artistas/:idArtista",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosArtistasIdArtistaDelete,
		},
		{
			"UsuariosIdUsuarioFavoritosArtistasIdArtistaPost",
			http.MethodPost,
			"/usuarios/:idUsuario/favoritos/artistas/:idArtista",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosArtistasIdArtistaPost,
		},
		{
			"UsuariosIdUsuarioFavoritosCancionesGet",
			http.MethodGet,
			"/usuarios/:idUsuario/favoritos/canciones",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosCancionesGet,
		},
		{
			"UsuariosIdUsuarioFavoritosCancionesIdCancionDelete",
			http.MethodDelete,
			"/usuarios/:idUsuario/favoritos/canciones/:idCancion",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosCancionesIdCancionDelete,
		},
		{
			"UsuariosIdUsuarioFavoritosCancionesIdCancionPost",
			http.MethodPost,
			"/usuarios/:idUsuario/favoritos/canciones/:idCancion",
			handleFunctions.FavoritosAPI.UsuariosIdUsuarioFavoritosCancionesIdCancionPost,
		},
		{
			"ListasIdListaCancionesIdCancionDelete",
			http.MethodDelete,
			"/listas/:idLista/canciones/:idCancion",
			handleFunctions.ListasDeReproduccionAPI.ListasIdListaCancionesIdCancionDelete,
		},
		{
			"ListasIdListaCancionesIdCancionPost",
			http.MethodPost,
			"/listas/:idLista/canciones/:idCancion",
			handleFunctions.ListasDeReproduccionAPI.ListasIdListaCancionesIdCancionPost,
		},
		{
			"ListasIdListaDelete",
			http.MethodDelete,
			"/listas/:idLista",
			handleFunctions.ListasDeReproduccionAPI.ListasIdListaDelete,
		},
		{
			"ListasIdListaGet",
			http.MethodGet,
			"/listas/:idLista",
			handleFunctions.ListasDeReproduccionAPI.ListasIdListaGet,
		},
		{
			"ListasIdListaPatch",
			http.MethodPatch,
			"/listas/:idLista",
			handleFunctions.ListasDeReproduccionAPI.ListasIdListaPatch,
		},
		{
			"UsuariosIdUsuarioListasGet",
			http.MethodGet,
			"/usuarios/:idUsuario/listas",
			handleFunctions.ListasDeReproduccionAPI.UsuariosIdUsuarioListasGet,
		},
		{
			"UsuariosIdUsuarioListasPost",
			http.MethodPost,
			"/usuarios/:idUsuario/listas",
			handleFunctions.ListasDeReproduccionAPI.UsuariosIdUsuarioListasPost,
		},
		{
			"ComunidadesIdComunidadPostsGet",
			http.MethodGet,
			"/comunidades/:idComunidad/posts",
			handleFunctions.PostsDeComunidadAPI.ComunidadesIdComunidadPostsGet,
		},
		{
			"ComunidadesIdComunidadPostsPost",
			http.MethodPost,
			"/comunidades/:idComunidad/posts",
			handleFunctions.PostsDeComunidadAPI.ComunidadesIdComunidadPostsPost,
		},
		{
			"PostsIdPostDelete",
			http.MethodDelete,
			"/posts/:idPost",
			handleFunctions.PostsDeComunidadAPI.PostsIdPostDelete,
		},
		{
			"PostsIdPostGet",
			http.MethodGet,
			"/posts/:idPost",
			handleFunctions.PostsDeComunidadAPI.PostsIdPostGet,
		},
		{
			"PostsIdPostPatch",
			http.MethodPatch,
			"/posts/:idPost",
			handleFunctions.PostsDeComunidadAPI.PostsIdPostPatch,
		},
		{
			"PostsIdPostRespuestasGet",
			http.MethodGet,
			"/posts/:idPost/respuestas",
			handleFunctions.PostsDeComunidadAPI.PostsIdPostRespuestasGet,
		},
		{
			"UsuariosGet",
			http.MethodGet,
			"/usuarios",
			handleFunctions.UsuariosAPI.UsuariosGet,
		},
		{
			"UsuariosIdUsuarioDelete",
			http.MethodDelete,
			"/usuarios/:idUsuario",
			handleFunctions.UsuariosAPI.UsuariosIdUsuarioDelete,
		},
		{
			"UsuariosIdUsuarioGet",
			http.MethodGet,
			"/usuarios/:idUsuario",
			handleFunctions.UsuariosAPI.UsuariosIdUsuarioGet,
		},
		{
			"UsuariosIdUsuarioPatch",
			http.MethodPatch,
			"/usuarios/:idUsuario",
			handleFunctions.UsuariosAPI.UsuariosIdUsuarioPatch,
		},
		{
			"UsuariosPost",
			http.MethodPost,
			"/usuarios",
			handleFunctions.UsuariosAPI.UsuariosPost,
		},
	}
}
